# Generated by Django 6.0.6 on 2026-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('avialable', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food images')),
            ],
        ),
    ]
