# Generated by Django 6.0.6 on 2026-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_fooddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
