# Generated by Django 6.0.6 on 2026-07-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_fooddb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_age', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_place', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_email', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Profile images')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
