# Generated by Django 6.0.6 on 2026-07-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_staffdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdb',
            old_name='staff_place',
            new_name='staff_Address',
        ),
    ]
