# Generated by Django 6.0.6 on 2026-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_rename_staff_place_staffdb_staff_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Reser_date', models.CharField(blank=True, max_length=100, null=True)),
                ('Reser_time', models.CharField(blank=True, max_length=100, null=True)),
                ('table_num', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_no', models.IntegerField(blank=True, null=True)),
                ('Capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffdb',
            name='staff_Address',
        ),
    ]
