# Generated by Django 6.0.6 on 2026-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_reservationdb_table_remove_staffdb_staff_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_no', models.IntegerField(blank=True, null=True)),
                ('Capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
