# Generated by Django 6.0.6 on 2026-08-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_tabledb_delete_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledb',
            name='active',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
