# Generated by Django 6.0.6 on 2026-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_tabledb_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledb',
            name='Table_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
