# Generated by Django 6.0.6 on 2026-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_alter_tabledb_table_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Table_no', models.CharField(max_length=100)),
                ('Capacity', models.IntegerField()),
                ('Booking_Date', models.DateField()),
                ('Booking_Time', models.TimeField()),
                ('Members', models.IntegerField()),
                ('Status', models.CharField(default='Booked', max_length=50)),
            ],
        ),
    ]
