# Generated by Django 6.0.6 on 2026-08-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_reservationdb_table_remove_staffdb_staff_address'),
        ('WebApp', '0002_registrationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Total_Price', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.fooddb')),
            ],
        ),
    ]
