# Generated by Django 6.0.6 on 2026-08-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_reservationdb_table_remove_staffdb_staff_address'),
        ('WebApp', '0003_cartdbmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.PositiveIntegerField()),
                ('Total_Price', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Payment', models.CharField(max_length=50)),
                ('Ordered_Date', models.DateTimeField(auto_now_add=True)),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.fooddb')),
            ],
        ),
    ]
