# Generated by Django 6.0.6 on 2026-08-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_tablebooking'),
        ('WebApp', '0006_bookingdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tabledb'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
