# Generated by Django 6.0.6 on 2026-08-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_alter_bookingdb_table_delete_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20),
        ),
    ]
