# Generated by Django 6.0.6 on 2026-08-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_alter_bookingdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
