# Generated by Django 6.0.6 on 2026-08-04 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_tablebooking'),
        ('WebApp', '0009_bookingdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Payment', models.CharField(max_length=50)),
                ('Grand_Total', models.IntegerField()),
                ('Ordered_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total_Price', models.IntegerField()),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.fooddb')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
