# Generated by Django 6.0.6 on 2026-08-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_order_orderitem_delete_ordermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
    ]
